'use client';
import {useEffect,useRef,useState} from 'react';
import BrandReason from '../components/BrandReason';
import AdPlayer, {AdPlayerHandle} from '../components/AdPlayer';
import {API,Analysis,Brand,Config,Debug,Decision,Episode,Job,request,timecode,uploadEpisode} from '../lib/api';

const terminal=(job:Job)=>['COMPLETED','FAILED','CANCELLED'].includes(job.status);
const stageNames:Record<string,string>={QUEUED:'Waiting for a worker',INGESTING:'Checking episode',SCENE_DETECTION:'Detecting visual cuts',TRANSCRIBING:'Listening to dialogue',CANDIDATE_GENERATION:'Checking speech safety',SEMANTIC_ANALYSIS:'Understanding scenes',BREAK_OPTIMIZATION:'Balancing the schedule',BRAND_MATCHING:'Preparing your results',COMPLETED:'Ready to review',FAILED:'Analysis interrupted',CANCELLED:'Cancelled'};

export default function Page(){
  const [authenticated,setAuthenticated]=useState<boolean|null>(null);
  const [config,setConfig]=useState<Config|null>(null);
  const [password,setPassword]=useState('');
  const [episodes,setEpisodes]=useState<Episode[]>([]);
  const [brands,setBrands]=useState<Brand[]>([]);
  const [view,setView]=useState<'workspace'|'brands'>('workspace');
  const [job,setJob]=useState<Job|null>(null);
  const [analysis,setAnalysis]=useState<Analysis|null>(null);
  const [debug,setDebug]=useState<Debug|null>(null);
  const [file,setFile]=useState<File|null>(null);
  const [uploading,setUploading]=useState(false);
  const [uploadProgress,setUploadProgress]=useState(0);
  const [error,setError]=useState('');
  const [filter,setFilter]=useState<'all'|'accepted'|'blocked'>('all');
  const [selected,setSelected]=useState<Decision|null>(null);
  const [loading,setLoading]=useState(false);
  const [episodeName,setEpisodeName]=useState('Episode review');
  const player=useRef<AdPlayerHandle>(null);
  const uploadAbort=useRef<AbortController|null>(null);
  const busy=uploading||Boolean(job&&!terminal(job));

  async function refresh(){await Promise.all([request<{items:Episode[]}>('/api/videos').then(library=>setEpisodes(library.items)),request<Brand[]>('/api/brands').then(setBrands)]);}
  async function loadResults(id:string){setLoading(true);setError('');try{const [a,d]=await Promise.all([request<Analysis>(`/api/videos/${id}/analysis`),request<Debug>(`/api/videos/${id}/debug`)]);setAnalysis(a);setDebug(d);setSelected(null);window.history.replaceState({},'',`?video=${encodeURIComponent(id)}`);}finally{setLoading(false);}}
  useEffect(()=>{void Promise.all([request<Config>('/api/config'),request<{authenticated:boolean}>('/api/session')]).then(([c,s])=>{setConfig(c);setAuthenticated(s.authenticated);}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!authenticated)return;void refresh().catch(e=>setError(e.message));const id=new URLSearchParams(window.location.search).get('video');if(id)void loadResults(id).catch(e=>setError(e.message));},[authenticated]);
  useEffect(()=>{if(!job||terminal(job))return;let cancelled=false;const timer=setTimeout(()=>{void request<Job>(`/api/jobs/${job.id}`).then(async next=>{if(cancelled)return;setJob(next);if(next.status==='COMPLETED'){await loadResults(next.video_id);await refresh();}else if(next.status==='FAILED'){setError(`${next.error_stage}: ${next.error_code}`);await refresh();}}).catch(e=>{if(!cancelled){setError(e.message);setJob({...job});}});},2000);return()=>{cancelled=true;clearTimeout(timer);};},[job]);

  async function login(event:React.FormEvent){event.preventDefault();setError('');try{await request('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});setPassword('');setAuthenticated(true);}catch(e){setError(String(e));}}
  async function upload(){if(!file||!config)return;if(file.size>config.max_upload_mb*1024**2){setError(`Choose a file under ${config.max_upload_mb} MB.`);return;}setUploading(true);setUploadProgress(0);setError('');setAnalysis(null);setDebug(null);setJob(null);setEpisodeName(file.name);uploadAbort.current=new AbortController();try{const result=await uploadEpisode(file,setUploadProgress,uploadAbort.current.signal);setJob(result.job);setUploading(false);await refresh();}catch(e){setError(String(e));}finally{setUploading(false);}}
  async function openEpisode(episode:Episode){setView('workspace');setEpisodeName(episode.metadata.filename||'Episode');setJob(episode.job);setAnalysis(null);setDebug(null);setError('');if(episode.job?.status==='COMPLETED')await loadResults(episode.id).catch(e=>setError(e.message));}
  async function retry(){if(!job)return;try{const next=await request<Job>(`/api/videos/${job.video_id}/analyze?force=true`,{method:'POST'});setJob(next);setError('');}catch(e){setError(String(e));}}
  async function cancel(){if(uploading&&!job){uploadAbort.current?.abort();return;}if(job){try{setJob(await request<Job>(`/api/jobs/${job.id}/cancel`,{method:'POST'}));await refresh();}catch(e){setError(String(e));}}}
  function seek(seconds:number){const video=document.querySelector<HTMLVideoElement>('[data-testid="content-video"]');if(video){video.currentTime=seconds;video.scrollIntoView({behavior:'smooth',block:'center'});}}
  const decisions=(debug?.decisions||[]).filter(d=>filter==='all'||(filter==='accepted'?d.accepted:d.debug?.hard_blocked)).sort((a,b)=>(a.debug?.rank??Infinity)-(b.debug?.rank??Infinity)||a.timestamp_sec-b.timestamp_sec);
  const activeEpisode=episodes.find(e=>e.id===analysis?.video.id);

  if(authenticated===false)return <main className="login-shell"><div className="wordmark">interlude<span>●</span></div><form className="login-card" onSubmit={login}><p className="eyebrow">TEAM WORKSPACE</p><h1>A better place<br/>for a break.</h1><p>Sign in to analyze episodes and review contextual ad placements.</p><label>Workspace password<input autoFocus type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" type="submit">Enter workspace <span>↗</span></button>{error&&<p role="alert">{error}</p>}</form></main>;
  return <div className="app-shell"><aside className="sidebar"><a className="wordmark" href="/">interlude<span>●</span></a><div className="workspace-label"><span className="workspace-icon">I</span><div>Episode studio<small>Team workspace</small></div></div><nav aria-label="Workspace"><button className={view==='workspace'?'nav-item active':'nav-item'} onClick={()=>setView('workspace')}><span>▤</span> Episodes</button><button className={view==='brands'?'nav-item active':'nav-item'} onClick={()=>setView('brands')}><span>◈</span> Brand catalogue <small>{brands.length}</small></button></nav><div className="sidebar-bottom"><span className="status-dot"/> Safety checks enabled<p>Speech and brand exclusions always take priority.</p>{config?.protected&&<button className="text-button" onClick={()=>void request('/api/session/logout',{method:'POST'}).then(()=>setAuthenticated(false))}>Sign out ↗</button>}</div></aside>
  <main className="workspace-main"><header className="topbar"><span>Workspace <i>/</i> {view==='brands'?'Brand catalogue':'Episodes'}</span><span className="system-pill">Bengali · contextual placement</span></header>
  {error&&<div role="alert" className="error-banner">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
  {authenticated===null&&<p className="loading" role="status">Connecting to workspace…</p>}
  {view==='brands'?<><div className="page-heading"><div><p className="eyebrow">CONTEXT, NOT GUESSWORK</p><h1>Brand catalogue</h1><p>Activity drives relevance. Negative contexts are absolute exclusions.</p></div><span className="count-label">{brands.length} synthetic brands</span></div><div className="brand-grid">{brands.map((b,i)=><article className="brand-card" key={b.brand_id}><div className={`brand-monogram tone-${i%4}`}>{b.display_name.replace('Brand ','')}</div><h2>{b.display_name}</h2><p>{b.category}</p><h3>Relevant contexts</h3><div className="tags">{b.target_contexts.map(c=><span key={c}>{c}</span>)}</div><h3>Never place against</h3><div className="tags negative">{b.negative_contexts.map(c=><span key={c}>{c}</span>)}</div></article>)}</div></>:<>
  <div className="page-heading"><div><p className="eyebrow">EVERY BREAK HAS A REASON</p><h1>Your episodes, intelligently placed.</h1><p>Understand the story. Find a natural pause. Match the right brand.</p></div><span className="count-label">{episodes.length} recent episodes</span></div>
  <section className="upload-panel" aria-label="Upload episode"><div className="upload-icon">↑</div><div className="upload-copy"><h2>Bring in the whole episode.</h2><p>H.264 MP4 with audio · up to {config?Math.round(config.max_video_duration_sec/60):'…'} minutes · {config?(config.max_upload_mb/1024).toFixed(0):'…'} GB</p><label className="file-label">{file?file.name:'Choose a video file'}<input aria-label="Choose episode" type="file" accept="video/mp4,.mp4" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><button className="primary" disabled={!file||busy||!authenticated} onClick={()=>void upload()}>{uploading?'Uploading…':'Analyze episode'} <span>↗</span></button></section>
  {(busy||job?.status==='FAILED'||job?.status==='CANCELLED')&&<section className="progress-panel" aria-live="polite"><div><span className={busy?'spinner':'status-dot'}/><h2>{uploading?`Uploading ${uploadProgress}%`:stageNames[job?.status||'']}</h2><p>{uploading?'Keep this tab open until the upload finishes.':'Analysis runs in the background. You can return to this episode later.'}</p></div><div className="progress-detail">{job?.progress?.total?<><span>{job.progress.completed} / {job.progress.total} {job.progress.stage?.replaceAll('_',' ')}</span><progress value={job.progress.completed} max={job.progress.total}/></>:uploading?<progress value={uploadProgress} max={100}/>:busy?<progress/>:null}{busy?<button className="text-button" onClick={()=>void cancel()}>Cancel</button>:<button className="secondary" onClick={()=>void retry()}>Retry analysis</button>}</div></section>}
  {loading&&<p role="status" className="loading">Loading analysis…</p>}
  {analysis&&debug&&<section className="review"><div className="section-heading"><div><p className="eyebrow">EPISODE REVIEW</p><h2>{activeEpisode?.metadata.filename||episodeName}</h2></div><div className="downloads"><a href={`${API}/api/videos/${analysis.video.id}/vmap`} download>↓ VMAP</a><a href={`${API}/api/videos/${analysis.video.id}/debug`} download>↓ Debug JSON</a><a href={`${API}/api/videos/${analysis.video.id}/scenes`} download>↓ Scenes</a><a href={`${API}/api/videos/${analysis.video.id}/candidates`} download>↓ Candidates</a></div></div>
  <div className="metrics"><div><span>Episode length</span><strong>{timecode(analysis.video.duration_sec)}</strong></div><div><span>Semantic scenes</span><strong>{analysis.summary.scene_count}</strong></div><div><span>Break candidates</span><strong>{analysis.summary.candidate_count}</strong></div><div className="highlight-metric"><span>Selected placements</span><strong>{analysis.ad_breaks.length}<small> / {((analysis.ad_breaks.reduce((n,b)=>n+b.duration_sec,0)/analysis.video.duration_sec)*100).toFixed(1)}% ad load</small></strong></div></div>
  <div className="player-layout"><div className="player-card"><AdPlayer ref={player} key={analysis.video.id} source={analysis.video.source_url} breaks={analysis.ad_breaks}/><div className="timeline" aria-label="Semantic scene timeline">{debug.scenes?.map((scene,i)=><button key={scene.id} style={{width:`${(scene.end_sec-scene.start_sec)/analysis.video.duration_sec*100}%`}} title={`Scene ${i+1} · ${timecode(scene.start_sec)}–${timecode(scene.end_sec)}`} aria-label={`Seek to scene ${i+1}`} onClick={()=>seek(scene.start_sec)} className={`scene-segment tone-${i%4}`}/>)}{analysis.ad_breaks.map(b=><span key={b.candidate_id} className="break-marker" style={{left:`${b.timestamp_sec/analysis.video.duration_sec*100}%`}} title={`Ad · ${timecode(b.timestamp_sec)}`}/>)}</div><div className="timeline-labels"><span>00:00</span><span><i/> Semantic scenes <b/> Selected breaks</span><span>{timecode(analysis.video.duration_sec)}</span></div></div><aside className="schedule-card"><p className="eyebrow">THE FINAL SCHEDULE</p><h2>Room for a break.</h2>{analysis.ad_breaks.length===0?<p className="empty-copy">No safe opportunity cleared the quality and pacing checks. Review the candidate reasons below.</p>:analysis.ad_breaks.map((b,i)=><button className="schedule-item" key={b.candidate_id} onClick={()=>{setSelected(debug.decisions.find(d=>d.candidate_id===b.candidate_id)||null);player.current?.preview(b.candidate_id);document.querySelector('[aria-label="Content and advertisement player"]')?.scrollIntoView({behavior:'smooth',block:'center'});}}><span className="schedule-number">{String(i+1).padStart(2,'0')}</span><div><strong>{timecode(b.timestamp_sec)}</strong><small>{brands.find(v=>v.brand_id===b.brand_id)?.display_name||b.brand_id} · {b.duration_sec}s</small></div><span>↗</span></button>)}<p className="schedule-note">Each placement passes speech, brand safety and episode-wide pacing checks.</p></aside></div>
  <div className="section-heading candidates-heading"><div><p className="eyebrow">TRANSPARENT DECISIONS</p><h2>Every opportunity, explained.</h2></div><div className="tabs" role="group" aria-label="Filter candidates">{(['all','accepted','blocked'] as const).map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='all'?'All candidates':f==='accepted'?'Selected':'Safety blocked'}</button>)}</div></div>
  <div className="candidate-layout"><div className="table-scroll"><table><thead><tr><th>Rank / time</th><th>Decision</th><th>WHERE score</th><th>Reason</th><th/></tr></thead><tbody>{decisions.map(d=><tr className={selected?.candidate_id===d.candidate_id?'selected-row':''} key={d.candidate_id}><td><span className="rank">{d.debug?.rank?`#${d.debug.rank}`:'—'}</span> {timecode(d.timestamp_sec)}</td><td><span className={`badge ${d.accepted?'accepted':d.debug?.hard_blocked?'blocked':'rejected'}`}>{d.accepted?'Selected':d.debug?.hard_blocked?'Safety blocked':'Not selected'}</span></td><td><div className="score-cell"><strong>{d.where_score.toFixed(3)}</strong><span style={{width:`${d.where_score*60}px`}}/></div></td><td className="reason-cell">{d.accepted?'Safe opportunity · selected globally':d.rejection_reasons.map(r=>r.replaceAll('_',' ')).join(' · ')}</td><td><button aria-label={`Inspect candidate at ${d.timestamp_sec} seconds`} className="inspect-button" onClick={()=>setSelected(d)}>↗</button></td></tr>)}</tbody></table>{decisions.length===0&&<p className="empty-copy">No candidates in this view.</p>}</div><aside className="decision-detail">{selected?<><p className="eyebrow">CANDIDATE DETAIL</p><h2>{timecode(selected.timestamp_sec)} <small>{selected.where_score.toFixed(3)}</small></h2><p>{selected.semantics?.dominant_activity||'Stopped by speech safety before placement scoring.'}</p>{Object.entries(selected.debug?.where?.components||{}).map(([key,value])=><div className="component" key={key}><span>{key.replaceAll('_',' ')}</span><strong>{value.toFixed(2)}</strong><progress value={value} max={1}/></div>)}{Boolean(selected.debug?.where?.sequence_interruption_penalty)&&<p>Ongoing sequence adjustment: −{selected.debug!.where!.sequence_interruption_penalty!.toFixed(3)}</p>}<h3>Brand eligibility</h3>{selected.debug?.brands?.map(b=><div className="brand-verdict" key={b.brand_id}><strong>{brands.find(x=>x.brand_id===b.brand_id)?.display_name||b.brand_id}</strong><span>{b.eligible?b.score?.toFixed(3):'Blocked'}</span>{b.hard_blocks.length>0&&<small>{b.hard_blocks.join(', ')}</small>}</div>)}{selected.accepted&&<BrandReason key={selected.candidate_id} videoId={analysis.video.id} candidateId={selected.candidate_id}/>}<button className="secondary" onClick={()=>seek(Math.max(0,selected.timestamp_sec-3))}>Review this moment ↗</button></>:<><span className="detail-icon">◎</span><h3>See the reasoning.</h3><p>Select a candidate to inspect its weighted signals and brand safety checks.</p></>}</aside></div>
  <details className="scene-list"><summary>Explore {debug.scenes?.length||0} semantic scenes</summary><div>{debug.scenes?.map((s,i)=><button key={s.id} onClick={()=>seek(s.start_sec)}><span>Scene {String(i+1).padStart(2,'0')}</span><strong>{timecode(s.start_sec)} — {timecode(s.end_sec)}</strong><small>{s.shot_ids.length} shots · {s.grouping_reasons[0]?.replaceAll('_',' ')}</small></button>)}</div></details></section>}
  <section className="library"><div className="section-heading"><div><p className="eyebrow">YOUR WORKSPACE</p><h2>Recent episodes</h2></div><button className="text-button" onClick={()=>void refresh().catch(e=>setError(e.message))}>Refresh ↻</button></div>{episodes.length===0?<div className="empty-library"><span>▤</span><h3>The next story starts here.</h3><p>Upload an episode to build its scene map and contextual ad schedule.</p></div>:<div className="episode-grid">{episodes.map((e,i)=><button key={e.id} className="episode-card" disabled={busy} onClick={()=>void openEpisode(e)}><div className={`episode-art tone-${i%4}`}><span>EPISODE</span><strong>{timecode(e.metadata.duration_sec)}</strong><i>↗</i></div><div className="episode-info"><h3>{e.metadata.filename||`Episode ${e.id.slice(0,8)}`}</h3><p><span className={`badge ${e.job?.status==='COMPLETED'?'accepted':e.job?.status==='FAILED'?'blocked':'rejected'}`}>{e.job?stageNames[e.job.status]||e.job.status:'Uploaded'}</span><small>{new Date(e.created_at+'Z').toLocaleDateString()}</small></p>{!e.media_available&&<small>Source media expired</small>}</div></button>)}</div>}</section>
  </>}<footer>INTERLUDE <span>Thoughtful interruptions. Context comes first.</span><span>Workspace v3.0</span></footer></main></div>;
}
